### ISSUE TITLE
"Permission denied" error when init.d tries to start the service

### ISSUE THREAD

**Issue by saulp** [mdevilliers/vagrant-redis#4]
Hi Mark,

I hope you'll forgive my newb question. I am getting the following error as the last step of "vagrant up":

==> default: /tmp/vagrant-shell: line 28: /etc/init.d/redis_6379: Permission denied

After logging in the box, the script has no executable permissions.

I've addressed this by running:
sudo chmod a+x /etc/init.d/redis_6379
sudo /etc/init.d/redis_6379 start

(Both commands needed to be run with sudo)

P.S. Thanks for sharing these scripts!

**Comment by saulp** [comment]
Note: This is pretty much a non-issue as it can be easily addressed by making the redis.init.d script executable. Closing it up, thanks again Mark!

**Comment by mdevilliers** [comment]
Hey Saul - thanks for reporting the issue,

FYI I've added a line to correct the permission to the service so hopefully this won't be an issue in the future.

Mark
