### ISSUE TITLE
DENIED Redis is running in protected mode

### ISSUE THREAD

**Issue by MerouaneBen** [mdevilliers/vagrant-redis#6]
hi, 
I'm trying to use the box from the host but get this error 

(error) DENIED Redis is running in protected mode because protected mode is enabled, no bind address was specified, no authentication password is requested to clients. In this mode connections are only accepted from the loopback interface. If you want to connect from external computers to Redis you may adopt one of the following solutions: 1) Just disable protected mode sending the command 'CONFIG SET protected-mode no' from the loopback interface by connecting to Redis from the same host the server is running, however MAKE SURE Redis is not publicly accessible from internet if you do so. Use CONFIG REWRITE to make this change permanent. 2) Alternatively you can just disable the protected mode by editing the Redis configuration file, and setting the protected mode option to 'no', and then restarting the server. 3) If you started the server manually just for testing, restart it with the '--protected-mode no' option. 4) Setup a bind address or an authentication password. NOTE: You only need to do one of the above things in order for the server to start accepting connections from the outside.

 any help please, 
thanks

**Comment by mdevilliers** [comment]
Sorry for not getting back to you sooner.

Have you tried running the command as suggested e.g in the redis cli ?

**Comment by MerouaneBen** [comment]
yeah, I've tried redis-cli and it works, I mean I can connect to Redis from the host wheather from bash terminal or from python, but when I try to add data or query **Keys *** to the database I get this error. 
Note : I get this error only when I use it  from host, from inside the Vagrant VM everything works fine.

**Comment by mdevilliers** [comment]
Thanks

Could you try another branch - https://github.com/mdevilliers/vagrant-redis/tree/protected-mode?

I've added the key it wants to the config. I've tried it and it works but would just appreciate another set of eyes.

Thanks

Mark

**Comment by joshhendo** [comment]
I was going to make a PR with this change myself until I saw it in this branch. The change in the branch works well for me 👍

**Comment by mdevilliers** [comment]
Awesome, I'll merge it in.

Thanks
